project3/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone = True), default = func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(150), unique = True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

project3/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'HAI THIS IS MY FIRST FLASKAPP'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix = '/')
    app.register_blueprint(auth, url_prefix = '/')

    from .models import  User, Note
    # create_database(app)
    with app.app_context():
        db.create_all()


    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


# def create_database(app):
#     if not path.exists('website/' + DB_NAME):
#         db.create_all(app=app)
#         print('Created Database!')

# def create_database(app):
#     if not path.exists('website/' + DB_NAME):
#         db.create_all(app=app)
#         print('Created Database!')

project3/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user,  login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method =='POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email = email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('logged in Succesful', category = 'success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again. ', category = 'error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user = current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))
    # return render_template("logout.html") 

@auth.route('/singup', methods = ['GET', 'POST'])
def signup():
   
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstname')
        # password2 = request.form.get('password1')
        # password1 = request.form.get('password2')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        print('Email',email, 'fname', first_name, 'password1', password1 , 'password2', password2 )
        
        user = User.query.filter_by(email = email).first()
        if user:
            flash('Email already exists.', category = 'error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category ='error')
        elif len(first_name) < 2:
            flash('Email must be greater than 1 characters.', category ='error')
        elif password1 != password2: 
            flash("Passwords don't match.", category ='error')
        elif len(password1) < 7:
            flash('Passwords must be greater than 7 characters.', category ='error')
        else:
            new_user = User(email=email, first_name =first_name, password = generate_password_hash(password1, method = 'sha256')  )
            db.session.add(new_user)
            db.session.commit()
            login_user(user, remember=True)
            flash('Account created succesfully.', category='success')
            return redirect(url_for('views.home'))

  
    return render_template("signup.html", user = current_user)

project3/website/views.py
from flask import Blueprint, render_template, flash, request, jsonify, json
from flask_login import login_required,  current_user
from .models import Note
from .import db

views = Blueprint('views', __name__)


@views.route('/')
@views.route('index')
@login_required
def home():
    return render_template("app/home.html", name = 'Kavin', age= '45', user = current_user)


@views.route('service')
def service():
    return render_template("app/service.html", user = current_user)


@views.route('product')
def product():
    return render_template("app/product.html", user = current_user)

@views.route('about')
def about():
    flash('This is a flash error message', 'error')
    flash('This is a flash Sucess message', 'Success')
    return render_template('app/about.html', user = current_user)


@views.route('notes',methods = ['GET', 'POST'])
def note():
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) < 1:
            flash("Note is too short", category = 'error')
        else:
            new_note = Note(data = note, user_id = current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash("note is added", category = 'success')


    return render_template('app/note.html', user = current_user)

@views.route('/delete-note', methods = ['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)    
    print(current_user.id)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

project3/website/templates/app/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% extends 'base.html' %}
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> -->

</head>
<body>
    {% block content %}

   This is about page.

    {% endblock %}
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->

</body>
</html>

project3/website/templates/app/home.html
{% extends 'base.html'%}



{% block content %}

This is a home page.

<h1>Name is :{{name}}<br><br> And age is : {{age}}
</h1>

{% endblock %}

project3/website/templates/app/note.html
{% extends 'base.html'%}
{% block title %}
Note
{% endblock %}


{% block content %}

<h1 align = "center">Notes</h1>
<ul class = "list-group list-group-flush" id = "notes">
    {% for note in user.notes %}
       <li class = "list-group-item "> {{ note.data }} </li> 
            <button type="button" class = "close" onClick="deleteNote({{ note.id }})">
            <span aria-hidden="true">&times;</span>
       </button>
    {% endfor %}
</ul>

<form method="post">
    <textarea name = 'note' id = 'note' class = 'form-control'></textarea>
    <div align = "center">
        <button type = "submit" class = "btn btn-primary">Add Note </button>
    </div>
</form>

{% endblock %}

project3/website/templates/app/product.html
{% extends 'base.html'%}



{% block content %}


This is a Products page.

{% endblock %}

project3/website/templates/app/service.html
{% extends 'base.html'%}



{% block content %}


This is a Service page.

{% endblock %}

project3/website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{% block title %} Flask web page. {% endblock %}</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  
      <script type="text/javascript" src=" {{ url_for('static', filename = 'index.js') }}"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg" style="background-color: #7633f9;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('views.home') }}">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
             </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.service') }}">Service</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.product') }}">Products</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.about') }}">about</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.note') }}">Notes</a>
              </li>



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Page
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Log-out</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Log-in</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('auth.signup') }}">Signup</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                      {% if category == 'error' %}

                            <!-- for danger messages -->
                            <div class = 'alert alert-danger alert-dismissable fade show' role = "alert">
                                  {{ message }}
                                  <button type = 'button' class = 'close' data-dismiss="alert">
                                    <span aria-hidden="true">&times; 

                                    </span>
                                  </button>
                            </div>
                      {% else %}
                            <!-- for danger messages -->
                            <div class = 'alert alert-success alert-dismissable fade show' role = "alert">
                                  {{ message }}
                                  <button type = 'button' class = 'close' data-dismiss="alert">
                                    <span aria-hidden="true">&times;

                                    </span>
                                  </button>
                            </div>
                      {% endif %}
            {% endfor %}
          {% endif %} 
      {% endwith %}

      
  
  
      {% block content %}
    {% endblock %}













    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
                            
  </body>
</html>

project3/website/templates/login.html
{% extends 'base.html'%}

{% block content %}


<br><br>
<h3>Login page.</h3>
    <div class="d-grid gap-10 " style="width : 500px; height: 300px">
	    <form class=" gap-10 bg-secondary text-seondary bg-opacity-50" method="post" method = "post">

			  <div class="p-3 form-group">
			    <label for="email" class="form-label ">Email address</label>
			    <input type="email" class="form-control " id="email" name = "email" placeholder="Enter Email address">			   
			  </div>              

              <div class="p-3 form-group">
			    <label for="password" class="form-label ">Password</label>
			    <input type="password" class="form-control " id="password" name = "password" placeholder="Enter Password">			   
			  </div>

              <br>

	  			<button type="submit" class="p-1 form-check-label btn btn-primary" style="margin-left: 2%; ">Login</button>
                <br><br>
		</form>
    </div>



{% endblock %}

project3/website/templates/logout.html
{% extends 'base.html'%}



{% block content %}


This is a logout page.

{% endblock %}

project3/website/templates/signup.html
{% extends 'base.html'%}


{% block content %}


          
    <h3> sign up Form</h3>
    <div class="d-grid gap-10 " style="width : 500px; height: 300px">
	    <form class=" gap-10 bg-secondary text-seondary bg-opacity-50" method = "post" >
			  <div class="p-3 form-group">
			    <label for="email" class="form-label ">Email address</label>
			    <input type="email" class="form-control " id="email" name = "email" placeholder="Enter Email address">			   
			  </div>

        <div class="p-3 form-group">
			    <label for="firstname" class="form-label ">First name</label>
			    <input type="text" class="form-control " id="firstname" name = "firstname" placeholder="Enter First Name">			   
			  </div>

        <div class="p-3 form-group">
			    <label for="password1" class="form-label ">Password</label>
			    <input type="password" class="form-control " id="password1" name = "password1" placeholder="Enter Password here">			   
			  </div>

        <div class="p-3 form-group">
			    <label for="password2" class="form-label ">Confirm password.</label>
			    <input type="password" class="form-control " id="password2" name = "password2" placeholder="Enter Confirm Password">			   
			  </div>
              <br>

	  			<button type="submit" class="p-1 form-check-label btn btn-primary" style="margin-left: 2%; ">Submit</button>
                <br><br>
		</form>
    </div>


{% endblock %}

<!-- <form method="post">
    <div  >
        <div class = "form-group">
            <h3 align = "center">
                This is a sign-up page.
            </h3>
        </div>
        <div class = "form-group">
            <h3>Forms</h3>
            <div class="d-grid gap-10 " style="width : 500px; height: 300px">
                <form style="mb-3" class=" gap-10 bg-secondary text-seondary bg-opacity-50" >
                      <div class="p-3">
                        <label for="exampleInputEmail1" class="form-label ">Email address</label>
                        <input type="email" class="form-control " id="exampleInputEmail1" aria-describedby="emailHelp">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                      </div>
                      <div class="p-3">
                        <label for="exampleInputPassword1" class="form-label ">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1">
                      </div>
        
                      <div class=" form-check ">
                        <input type="checkbox p-3" class="form-check-input border" id="exampleCheck1">
                        <label class="form-check-label " for="exampleCheck1">Check me out</label>
                      </div>
        
                          <button type="submit" class="p-1 form-check-label btn btn-dark" style="margin-left: 2%; padding-left: 10 %; ">Submit</button>
                </form>
            </div>
        </div><br>
        <div class = "form-group">
            <label for ='name'>Username</label>
            <input type = 'text' class = "form-control" id = "name" name = "name" placeholder="Choose your User name">
        </div><br>
        <div class = "form-group">
            <label for ='password1'>Password</label>
            <input type = 'password' class = "form-control" id = "password1" name = "password1" placeholder="Enter your Password">
        </div><br>
        <div class = "form-group">
            <label for ='password2'>Password (Confirm)</label>
            <input type = 'password' class = "form-control" id = "password2" name = "password2" placeholder="Confirm your Password">
        </div><br>
        <br><br>
        
        <button type="submit" class="btn btn-primary" value="submit" style="border-radius: 15px; width: 100px; color: black;">Submit</button>

    </div>





</form> -->

<!-- 
<form>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form> -->